/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ppl_dsl_deliszt_datastruct_scala_MeshLoader__ */

#ifndef _Included_ppl_dsl_deliszt_datastruct_scala_MeshLoader
#define _Included_ppl_dsl_deliszt_datastruct_scala_MeshLoader

#include "CRSMesh/CRSMesh.h"

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ppl_dsl_deliszt_datastruct_scala_MeshLoader
 * Method:    loadMesh
 * Signature: (Ljava/lang/String;)Lppl/dsl/deliszt/datastruct/scala/Mesh;
 */
JNIEXPORT jobject JNICALL Java_ppl_dsl_deliszt_datastruct_scala_MeshLoader_loadMesh
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ppl_dsl_deliszt_datastruct_scala_MeshLoader
 * Method:    loadBoundarySet
 * Signature: (Ljava/lang/String;I)Lppl/dsl/deliszt/datastruct/scala/BoundarySet;
 */
JNIEXPORT jobject JNICALL Java_ppl_dsl_deliszt_datastruct_scala_MeshLoader__1loadBoundarySet
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     ppl_dsl_deliszt_datastruct_scala_MeshLoader
 * Method:    loadMesh
 * Signature: (Ljava/lang/String;)Lppl/dsl/deliszt/datastruct/scala/Mesh;
 */
JNIEXPORT jobject JNICALL Java_generated_scala_MeshLoader_loadMesh
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ppl_dsl_deliszt_datastruct_scala_MeshLoader
 * Method:    _loadBoundarySet
 * Signature: (Ljava/lang/String;Lppl/dsl/deliszt/datastruct/scala/BoundarySetImpl;Lppl/dsl/deliszt/datastruct/scala/MeshObjConstruct;)Lppl/dsl/deliszt/datastruct/scala/BoundarySet;
 */
JNIEXPORT jobject JNICALL Java_generated_scala_MeshLoader__1loadBoundarySet
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
