package ppl.dsl.optiml.application

trait ApplicationOps extends PairwiseRatingOps with BiGGDetectionOps with BinarizedGradientPyramidOps with BinarizedGradientTemplateOps with RectOps
trait ApplicationOpsExp extends PairwiseRatingOpsExp with BiGGDetectionOpsExp with BinarizedGradientPyramidOpsExp with BinarizedGradientTemplateOpsExp with RectOpsExp
trait ScalaGenApplicationOps extends ScalaGenPairwiseRatingOps with ScalaGenBiGGDetectionOps with ScalaGenBinarizedGradientPyramidOps with ScalaGenBinarizedGradientTemplateOps with ScalaGenRectOps 
