

.PHONY: apps
apps:
	cd graph/pagerank && $(MAKE)
	cd graph/trianglecounting && $(MAKE)
	cd ml/gda && $(MAKE) -f Makefile.arma
	cd ml/kmeans && $(MAKE)
	cd ml/logreg && $(MAKE)
	cd ql && $(MAKE)
	cd wrangler && $(MAKE)

