package ppl.delite.runtime.scheduler

import java.util.ArrayDeque
import ppl.delite.runtime.codegen.DeliteExecutable
import ppl.delite.runtime.graph.ops.DeliteOP

/**
 * Author: Kevin J. Brown
 * Date: Oct 11, 2010
 * Time: 4:34:43 PM
 * 
 * Pervasive Parallelism Laboratory (PPL)
 * Stanford University
 */

/**
 * This class represents all the results generated by the walktime scheduler
 */
class StaticSchedule(val resources: Array[ArrayDeque[DeliteExecutable]]) {
  /**
   * Currently this class only holds a single scheduling object
   * The outer array represents the resources scheduled across
   * The inner ArrayDeque is the schedule for that resource
   * Designed to grow
   */
}

class PartialSchedule(val resources: Array[ArrayDeque[DeliteOP]]) {
  /**
   * Currently this class only holds a single scheduling object
   * The outer array represents the resources scheduled across
   * The inner ArrayDeque is the partial schedule of ops for that resource
   * Designed to grow
   */
}