/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ppl_dsl_deliszt_datastruct_scala_MeshLoader__ */

#ifndef _Included_ppl_dsl_deliszt_datastruct_scala_MeshLoader__
#define _Included_ppl_dsl_deliszt_datastruct_scala_MeshLoader__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ppl_dsl_deliszt_datastruct_scala_MeshLoader__
 * Method:    loadMesh
 * Signature: (Ljava/lang/String;)Lppl/dsl/deliszt/datastruct/scala/Mesh;
 */
JNIEXPORT jobject JNICALL Java_ppl_dsl_deliszt_datastruct_scala_MeshLoader_00024_loadMesh
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
