#!/bin/bash
script_dir="$(dirname "$0")"
java -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256m -XX:ReservedCodeCacheSize=256m -Xmx1024M -Xss2M -Djline.WindowsTerminal.directConsole=false -jar "$script_dir/sbt.jar" "$@"

