package ppl.delite.runtime.walktime.scheduler

import java.util.ArrayDeque
import ppl.delite.runtime.walktime.codegen.DeliteExecutable

/**
 * Author: Kevin J. Brown
 * Date: Oct 11, 2010
 * Time: 4:34:43 PM
 * 
 * Pervasive Parallelism Laboratory (PPL)
 * Stanford University
 */

/**
 * This class represents all the results generated by the walktime scheduler
 */
class StaticSchedule(val resources: Array[ArrayDeque[DeliteExecutable]]) {
  /**
   * Currently this class only holds a single scheduling object
   * The outer array represents the resources scheduled across
   * The inner ArrayDeque is the schedule for that resource
   * Designed to grow
   */
}